arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - arm_base_joint
       - shoulder_joint
       - bottom_wrist_joint
       - elbow_joint
       - top_wrist_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      hip: {trajectory: 0.1, goal: 0.1}
      shoulder: {trajectory: 0.1, goal: 0.1}
      elbow: {trajectory: 0.1, goal: 0.1}
      wrist: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10